name: Lab4 Add Testing To Pipeline

on:
  push:
    branches:
      - main
      - feature/**
      - solution
  pull_request:
    branches:
      - main

jobs:
  ci-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"

      - run: npm clean-install

      - name: Run Lint
        run: npm run lint

      - name: Run Unit Tests
        run: npm run unit-tests

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          directory: ./coverage
          files: coverage-final.json
          path_to_write_report: ./coverage/codecov_report.txt
          fail_ci_if_error: true
          flags: unittests
          verbose: true
          dry_run: true
          # REVISIT codecov uploads codecoverage stats to the site for comparisons across time
          # remove dry_run command, and add token: to enable this
          # https://github.com/marketplace/actions/codecov

  # REVISIT Validate Coverage & Store Artefact

  ci-integration-test:
    runs-on: ubuntu-latest
    # container: node:16
    services:
      mongodb:
        image: mongo:4.0
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"

      - run: npm clean-install
      - run: npm run integration-tests
        env:
          MONGO_URL: mongodb://localhost:27017/todos
          APP_PORT: 2000

      # - if: github.ref == 'refs/heads/main'
      #   run: npm pack

      # - if: github.ref == 'refs/heads/main'
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: node-todo-${{ github.sha }}
      #     path: ./*.tgz
